### ISSUE TITLE
Determine repositories for retrofit

### ISSUE THREAD

**Issue by dlowenberg** [CDLUC3/Make-Data-Count#84]
- [x] DataONE
- [x] Dash Portal (CDL)
- [x] KNB
- [x] Arctic Data Center

**Comment by rushirajnenuji** [comment]
To figure out which repositories would be fitted for adding the portable, pluggable widgets (offering front-end display for the new back-end source DLM information). Currently, the DLM display needs to be compatible with 2 repositories:
o	DataONE
o	Dash Portal (CDL)

**Comment by mbjones** [comment]
@rushirajnenuji I would add two more:

- KNB
- Arctic Data Center

Both of which are members of DataONE, and both of which use MetacatUI, so there shouldn't be extra development.  But including them lets us test the display in the context of specific repositories, rather than DataONE as an aggregator spanning repositories.

**Comment by mbjones** [comment]
It seems that discussion on these proposed repos has waned.  I think the proposal is non-controversial.  So moving it to review in prep of closing it as complete in terms of a decision.
