### ISSUE TITLE
Find candidate beta testers for log processor (i.e. Dataverse)

### ISSUE THREAD

**Issue by mbjones** [CDLUC3/Make-Data-Count#99]

**Comment by mbjones** [comment]
Contact DataVerse and other implementors to either use the log processing python script or develop their own.

**Comment by pdurbin** [comment]
@mbjones hi! I just picked up https://github.com/IQSS/dataverse/issues/4821 and I'm trying to learn enough about Make Data Count to start writing some code. I don't know yet if Dataverse will use the log processing Python script ( https://github.com/CDLUC3/counter-processor ). We did have a call with @dlowenberg and others on 2018-10-18 and she indicated that if we have questions, we should reach out to her. Please stay tuned and please feel free to follow along in that GitHub issue on the Dataverse side. Thanks.

**Comment by mbjones** [comment]
Sounds great, @pdurbin. Thanks!

**Comment by pdurbin** [comment]
@mbjones @dlowenberg hi, I just posted some thoughts at https://github.com/CDLUC3/counter-processor/issues/3 about how a prerequisite to using counter-processor is for our software (Dataverse) to emit logs into a particular format. Dataverse already records downloads in its database and while I doubt it makes sense to record views in our database due to the volume of views I feel like I should at least talk through possible approaches to collecting the data to generate the reports before saying more about whether it makes sense for us to try counter-processor or not. I'll be sure to circle back because making a decision on this is on my to do list at https://github.com/IQSS/dataverse/issues/4821#issuecomment-440327789

**Comment by pdurbin** [comment]
As mentioned at https://makedatacount.org/2019/02/28/repository-implementation-webinar-march-26-2019/ Dataverse is using Counter Processor in our implementation of Make Data Count. We merged https://github.com/IQSS/dataverse/pull/5329 and once we cut a release our guides will explain to Dataverse installations how to install Counter Processor and integrate it with Dataverse. Thanks for making Counter Processor open source
